### PR TITLE
Added Norwegian translations

### PR DESCRIPTION
**Pull request by paalge**
This pull request adds Norwegian translations to autoref.
I've kept the capital letters as for other languages.

### CODE REVIEW

**Comment by u-fischer** [comment]
Thank you for this. I'm looking at it. The code is imho okay, but it made me aware that the handling and coordination of shorthands could be improved: https://github.com/latex3/babel/issues/84

**Comment by paalge** [comment]
I agree that ther are some issues with the shorthands, and also with what should be capital. I have seen adaptations that spilt the `autoref` into two commands, `\autoref{}` and `\Autoref{}` where the first has everything in lowercase.

**Comment by paalge** [comment]
What is the status here. Do any changes need to be made?

**Comment by u-fischer** [comment]
No, the PR is fine. There are now three PR regarding the languages, so I started to rewrite the language support of autoref to externalize it from hyperref. The norsk part is already included. I will try to commit something during the week.

**Comment by paalge** [comment]
Thank you for the work

**Pull request merged**
