### PR TITLE
remove dependency on `etexcmds` package

### PR DESCRIPTION
**Pull request by muzimuzhi**
Just a blind deletion and movement of related code lines.

To be honest I didn't put time to read nor fully understand if the corresponding doc still describes the behavior of code well.

Locally tested with `l3build check`, only the two pdf-based tests with config `build-xetex.lua` fails due to different `/CreationDate` and the first part of font name(s).

### CODE REVIEW

**Comment by u-fischer** [comment]
sounds like a good plan. But doesn't the code still use \etex@unexpanded?? Shouldn't that be changed to \unexpanded?

**Comment by muzimuzhi** [comment]
> sounds like a good plan. But doesn't the code still use \etex@unexpanded?? Shouldn't that be changed to \unexpanded?

Oh I forgot to push (amended) local changes.

**Comment by u-fischer** [comment]
I think the xetex test failures are a l3build bug. Someone seems to have removed the epoch settings:

https://github.com/latex3/l3build/commit/e36f95c47b02d34ab6f3db8bb3c44b00bbca10b4#diff-593135098ccaf38b6e67ab4e0960713edbad21344be0fda56e5fc2d8840c7cddL797

**Comment by muzimuzhi** [comment]
BTW does the branch `cleanup-patches` play the role of the `develop` in latex2e repo? In other words, if I open a new PR (just an assumption), is `cleanup-patches` the suggested base branch?

**Comment by muzimuzhi** [comment]
> I think the xetex test failures are a l3build bug. Someone seems to have removed the epoch settings:
> 
> [latex3/l3build@e36f95c#diff-593135098ccaf38b6e67ab4e0960713edbad21344be0fda56e5fc2d8840c7cddL797](https://github.com/latex3/l3build/commit/e36f95c47b02d34ab6f3db8bb3c44b00bbca10b4#diff-593135098ccaf38b6e67ab4e0960713edbad21344be0fda56e5fc2d8840c7cddL797)

Indeed. With your fix in https://github.com/latex3/l3build/pull/270 applied, now `l3build check -c config-xetex` ends with "All checks passed".

**Comment by u-fischer** [comment]
> BTW does the branch `cleanup-patches` play the role of the `develop` in latex2e repo? In other words, if I open a new PR (just an assumption), is `cleanup-patches` the suggested base branch?

yes. It didn't started like this, but now it is. I will rename it to develop.

**Pull request merged**
