### PR TITLE
Creating TDS and documentation with build.lua

### PR DESCRIPTION
**Pull request by pablgonz**
Hi, I managed to run `hyperref` using only `l3build` :), I modified the `.gitignore` and `build.lua` file a bit. It is now possible to create the documentation and TDS package using only `l3build`. 

A small difference in creating the `zip` file (not in the `hyperref.tds` structure), is related to the `.pdf` files in the documentation that are now all inside `doc`. 

I haven't touched the test files, I've just been concerned with generating a correct installation (add a `.cfg` missing) and documentation.
Greetings

### CODE REVIEW

**Comment by davidcarlisle** [comment]
Thanks for this, I'd been putting off writing the wrapper to call htlatex but your `type_manual` function looks quite clean, thanks. I'm not sure if ctan have a preference on the location of the main manual pdf. Having it in doc seems sensible if it is OK with them, we can easily check.

 @josephwright  unless we wanted to abstract parts of html generation into l3build as we do for pdf doc, rather than having the build sequence explicit in the specialtypestting  table?

**Comment by pablgonz** [comment]
@davidcarlisle The small difference is that using `mkctan` creates this structure in the `hyperref.zip` file:

```
hyperref
├── hyperref
│   ├── backref.dtx
│   ├── backref.pdf
│   ├── bmhydoc.sty
│   ├── ChangeLog.txt
│   ├── doc
│   │   ├── backref.pdf
│   │   ├── cmmi10-22.gif
│   │   ├── cmsy10-21.gif
│   │   ├── hyperref.pdf
│   │   ├── manual2.html
│   │   ├── manual3.html
│   │   ├── manual4.html
│   │   ├── manual5.html
│   │   ├── manual6.html
│   │   ├── manual7.html
│   │   ├── manual.css
│   │   ├── manual.html
│   │   ├── manual.pdf
│   │   ├── nameref.pdf
│   │   ├── paper.pdf
│   │   └── slides.pdf
│   ├── hluatex.dtx
│   ├── hyperref.dtx
│   ├── hyperref.ins
│   ├── hyperref.pdf
│   ├── manifest.txt
│   ├── minitoc-hyper.sty
│   ├── nameref.dtx
│   ├── nameref.pdf
│   ├── ntheorem-hyper.sty
│   ├── paperslides99.zip
│   ├── README.md
│   └── xr-hyper.sty
└── hyperref.tds.zip
```

Using `l3build ctan` creates this structure in the `hyperref-ctan.zip` file:

```
hyperref-ctan
├── hyperref
│   ├── backref.dtx
│   ├── bmhydoc.sty
│   ├── ChangeLog.txt
│   ├── doc
│   │   ├── backref.pdf
│   │   ├── cmmi10-22.gif
│   │   ├── cmsy10-21.gif
│   │   ├── hyperref.pdf
│   │   ├── manual2.html
│   │   ├── manual3.html
│   │   ├── manual4.html
│   │   ├── manual5.html
│   │   ├── manual6.html
│   │   ├── manual7.html
│   │   ├── manual.css
│   │   ├── manual.html
│   │   ├── manual.pdf
│   │   ├── manual.tex
│   │   ├── nameref.pdf
│   │   ├── paper.pdf
│   │   └── slides.pdf
│   ├── fdl.tex
│   ├── hluatex.dtx
│   ├── hyperref.dtx
│   ├── hyperref.ins
│   ├── manifest.txt
│   ├── manual.tex
│   ├── minitoc-hyper.sty
│   ├── nameref.dtx
│   ├── ntheorem-hyper.sty
│   ├── paperslides99.zip
│   ├── README.md
│   └── xr-hyper.sty
└── hyperref.tds.zip
```
The `hyperref.tds.zip` files have identical structures, the difference is in the `hyperref` directory included in the `.zip` file, I think that the one generated by `l3build` is "more correct" (includes everything), but, when modifying this structure you must adjust what is described in `manifest.txt`.

**Comment by pablgonz** [comment]
@josephwright  I had to modify `.gitignore` to preserve the cleanliness and state of the repository, using `mkctan` creates a lot of files that can't be cleaned, I think @davidcarlisle should be blamed for this :)

With the use of `l3build` those lines are no longer necessary

**Comment by davidcarlisle** [comment]
@pablgonz  actually the extra lines would be problematic if using mkctan, it assumes that you will use `git clean` to clean up and adding the files to gitignore would prevent that. could you push a commit to revert the change to .gitignore then we can merge here otherwise I'll sort out locally tomorrow, thanks

**Comment by pablgonz** [comment]
@davidcarlisle Hi, I've reversed the changes in `.gitignore' (it was easier than I thought)

**Pull request merged**
