### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pablgonz**
Small modifications to make it compatible with https://www.ctan.org/markdown

### CODE REVIEW

**Comment by pablgonz** [comment]
The CTAN version of `markdown` does not work the same way as github, some things are interpreted differently (like the [...])

**Comment by davidcarlisle** [comment]
Thanks I'll take this PR, but adjust afterwards not to link to mirrors as (once you have been directed to a mirror) those links should be same-site not back to the central hub

**Comment by pablgonz** [comment]
I tried not to use mirrors, but, CTAN refuses to allow downloads of certain files from its central server (the same goes for `.pdf` files). 
Anyway, I missed some things that I now saw with more time: 
In line 109
```
\autoref names and puvnenc.def are:
```
more nice
```
`\autoref` names and `puvnenc.def` are:
```

**Comment by davidcarlisle** [comment]
On Fri, 24 Jan 2020 at 15:59, Pablo González Luengo <
notifications@github.com> wrote:

> I tried not to use mirrors, but, CTAN refuses to allow downloads of
> certain files from its central server (the same goes for .pdf files).
>

yes I knew that really (when awake:-)


Anyway, I missed some things that I now saw with more time:
>

I may re-write the whole thing anyway actually, the opening paragraph lists
back ends that no longer exist and doesn't mention any that people might
use these days, it's almost as if it was written in the 1990s....

**Pull request merged**
